repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: poetry run -m black quantfinlib
        language: python
        types: [python]
        stages: [commit]

      - id: auto-add-commit-push
        name: auto-add-commit-push
        entry: bash
        language: system
        stages: [commit]
        args:
          - -c
          - |
            git add.
            git commit -m "${GIT_COMMIT_MESSAGE:-modified files with black}"
            git push origin $(git rev-parse --abbrev-ref HEAD)
