version: 1
disable_existing_loggers: False

formatters:
  quantfinlib:
    format: "%(asctime)s - %(name)s - %(module)s:%(lineno)d - %(levelname)s - %(message)s"
    # datefmt: "%Y-%m-%d %H:%M:%S"

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: quantfinlib
    stream: ext://sys.stdout

  file:
    class: logging.FileHandler
    level: INFO
    formatter: quantfinlib
    filename: quantfinlib.log

loggers:
  main:
    level: DEBUG
    handlers: [console, file]
    propagate: no

root:
  level: INFO
  handlers: [console, file]
